### ISSUE TITLE
Add To-Do List

### ISSUE THREAD

**Issue by ananyag309** [Ayu-hack/Hacktoberfest2024-1#10]
A simple command-line to-do list application that allows users to add, remove, and view tasks.

**Comment by Anonymousarceus** [comment]
I would like to add solution for this . Please assign me this issue under hacktoberfest 2024.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on Linkedin
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Gungunmi12** [comment]
I would like to add the solution can u pls assign it to me
