### ISSUE TITLE
To Add Tic Tac Toe game

### ISSUE THREAD

**Issue by Mayank8881** [Ayu-hack/Hacktoberfest2024-1#105]
### Title:
**Build a Tic-Tac-Toe Game in Python**

#### Problem:
Create a console-based Tic-Tac-Toe game in Python that allows two players to take turns and play against each other.

#### Input:
- Players will take turns entering their moves.
- The board is represented as a 3x3 grid.
- Each player will enter their move as a row and column index (0, 1, or 2).

#### Constraints:
- The input should be validated to ensure:
  - The chosen cell is not already occupied.
  - The input is within the range of valid indices (0 to 2).

#### Output:
- Display the game board after each move.
- Announce the winner if one player wins, or declare a draw if all cells are filled without a winner.

#### Example:

**Input:**
```
Player 1, enter your move (row and column): 0 0
Player 2, enter your move (row and column): 0 1
Player 1, enter your move (row and column): 1 1
Player 2, enter your move (row and column): 0 2
Player 1, enter your move (row and column): 2 2
```

**Output:**
```
Current Board:
 X | X | X
---------
   | O |  
---------
   |   | O

Player 1 wins!
```

#### Request:
I would like to contribute this solution as part of Hacktoberfest. Please assign this issue to me and add the **Hacktoberfest** label.

Thank you!

---

Feel free to adjust any part of the template to better fit your needs!

**Comment by Ayu-hack** [comment]
Please bring something new n unique program or project.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
