### ISSUE TITLE
To Add Book Allocation or Allocate Books Problem using c++

### ISSUE THREAD

**Issue by moksha-hub** [Ayu-hack/Hacktoberfest2024-1#108]
Hello I am Interested in adding a DSA problem.
Which is important and solving it in CPP using Binary Search is easy approach 

i would love to assign it to me also with label of hacktoberfest helps me a lot.

ThankYou @Ayu-hack

**Comment by Ayu-hack** [comment]
Please share the screenshot of working in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
