### ISSUE TITLE
To add a Binary Tree problem to check whether 2 trees are symmetric or not.

### ISSUE THREAD

**Issue by tupur-29** [Ayu-hack/Hacktoberfest2024-1#111]
I want to add the solution to the binary tree symmetric problem in python.
Please assign me this task under Hacktober fest 2024

**Comment by Ayu-hack** [comment]
Please share the screenshot of working in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts!
