### ISSUE TITLE
Creating Encryption Decryption of Text By key which is defined by user. 

### ISSUE THREAD

**Issue by MrunalKashid02** [Ayu-hack/Hacktoberfest2024-1#112]
Hello @Ayu-hack
I am Participating Hacktoberfest 2024

Encryption Decryption of Text using key. The key is defined by user by use of that key user able encrypt the text. and using same key generated cipher text can be decrypt.

Thanks You !

**Comment by Ayu-hack** [comment]
Please share the screenshot of working in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts!

**Comment by MrunalKashid02** [comment]
oh sorry i'll do it.
