### ISSUE TITLE
Request to add English Dictionary web app using Dictionary Api

### ISSUE THREAD

**Issue by aakash-sharma25** [Ayu-hack/Hacktoberfest2024-1#115]
Hi @Ayu-hack
I am participating in Hacktoberfest 2024 and would like to contribute to it by adding English Dictionary Web app which gives the meaning and the pronunciation of the word which is searched . It uses  [Dictionary Api](https://dictionaryapi.dev/)  to generate the response .

I would appreciate it if you could assign me this issue under hacktoberfest24 label.

**Comment by Ayu-hack** [comment]
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts!
