### ISSUE TITLE
caesar cipher encrypter using c language

### ISSUE THREAD

**Issue by kartikey369-ind** [Ayu-hack/Hacktoberfest2024-1#12]
I do have a repo created on caesar previously so i can work on it again
https://github.com/kartikey369-ind/caesar

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on LinkedIn
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by kartikey369-ind** [comment]
done with the work please check my pr https://github.com/Ayu-hack/Hacktoberfest2024/pull/35
