### ISSUE TITLE
Weather App using Python Flask.

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [Ayu-hack/Hacktoberfest2024-1#125]
Weather App to Search for Weather Conditions by location which will fetch min, max temperature and humidity.
Also Place API to generate images of searched location.

**Comment by Ayu-hack** [comment]
Assigned.  ⭐ Star these repos to get your PR merged faster! 🚀 More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by SunkaraboinaPraveenKumar** [comment]
But Why is that Your Repo Showing Excluded in Hacktoberfest
![image](https://github.com/user-attachments/assets/69476df8-a55f-4647-938a-336adb75f753)
