### ISSUE TITLE
To add a problem of finding the median of 2 sorted arrays

### ISSUE THREAD

**Issue by tupur-29** [Ayu-hack/Hacktoberfest2024-1#127]
I want to provide the solution to this problem of finding the median of 2 sorted arrays in python.
Please assign me this task under Hacktober fest 2024

**Comment by Ayu-hack** [comment]
Assigned.  
⭐ Star these repos to get your PR merged faster! 🚀 More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Satyam-nitp** [comment]
please assign this to me @Ayu-hack

**Comment by Ankurcr7** [comment]
Hey, @Ayu-hack 
Can you assign me to this issue.
