### ISSUE TITLE
C++ problem  + OOPS in C++ 

### ISSUE THREAD

**Issue by priyanshu1976** [Ayu-hack/Hacktoberfest2024-1#131]
I have whole code for dsa and oops in c++ and java please assign me this issue under hacktoberfest accepted

**Comment by Ayu-hack** [comment]
Assigned.  
⭐ Star these repos to get your PR merged faster! 🚀 More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to tag me in your Hacktoberfest certificate or badges LinkedIn post! 😄
👉 Follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!

**Comment by Ayu-hack** [comment]
Please name the issue with something related to it.

**Comment by soumenmanik1911** [comment]
hey @Ayu-hack i am intersted to contribute something on this issue can you assign me this
