### ISSUE TITLE
Java: Linear Search and Binary Search

### ISSUE THREAD

**Issue by soumenmanik1911** [Ayu-hack/Hacktoberfest2024-1#135]
Find the median of two sorted arrays by efficiently merging them and determining the middle value(s) without fully combining the arrays.

**Comment by soumenmanik1911** [comment]
hey @Ayu-hack  i am interested to solving this issue can you assign me this.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏
