### ISSUE TITLE
Add comprehensive beginner friendly DSA notes in C++ along with beginner to advance level projects in C++ and most commonly asked interview questions 

### ISSUE THREAD

**Issue by abhisheksaxena15** [Ayu-hack/Hacktoberfest2024-1#137]
Hi there,

I have detailed notes on Data Structures and Algorithms (DSA) in C++, including clear explanations of sorting algorithms and other core concepts. Additionally, I've prepared some commonly asked DSA interview questions (focused on C++) to help others prepare effectively for job interviews. Also 50 C++ question to get a good command in C++

I would like to contribute by:

Adding detailed DSA notes in C++
Covering sorting algorithms like Linked list ,All the Sorting and Searching algorithms especially Quick Sort, Merge Sort, and more
Providing interview-level questions with solutions
These resources would help beginners and job seekers. If you find this contribution valuable, Please let me know if I can go ahead and start working on this.

Looking forward to your feedback!

Best regards,
Abhishek Saxena

@Ayu-hack please assign me this work under Hacktoberfest2024

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏
