### ISSUE TITLE
Health Ease System developed using C#

### ISSUE THREAD

**Issue by syedmaazsaeed** [Ayu-hack/Hacktoberfest2024-1#14]
@Ayu-hack   How are You !

I would like to contribute a C# project that I developed with great effort. It's very beginner-friendly and will be highly helpful for others.

 If you allow, I can fork your repository, add the C# project, and create a pull request for you to review.

 If you find it valuable, you can merge it into the main branch.

Also, will this repository be included in Hacktoberfest 2024? That's important for me as well. Looking forward to your response.

Best regards,
Syed Maaz Saeed

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by syedmaazsaeed** [comment]
Hi @Ayu-hack,

Thanks for the quick response and for assigning me! 😊

I’ve forked and starred your repository, and I’ve successfully uploaded my C# project. Please take a moment to review it, and if you find it valuable, kindly merge my pull request into the main branch

**Comment by syedmaazsaeed** [comment]
![Hacktoberfest](https://github.com/user-attachments/assets/3641cbd4-92fd-481b-bff5-8f33a9d26a50)

Hi @Ayu-hack 

You mentioned that this repository is part of Hacktoberfest 2024, but it seems it is not included. 

Could you please make it a part of Hacktoberfest 2024?

**Comment by syedmaazsaeed** [comment]
Hi @Ayu-hack 
Please merge this into the latest main branch, as the previous submission wasn't accepted correctly. Kindly check it and let me know. Thanks! (latest pull request)

https://github.com/Ayu-hack/Hacktoberfest2024-1/pull/157

#157 opened 13 minutes ago by [syedmaazsaeed](https://github.com/Ayu-hack/Hacktoberfest2024-1/issues?q=is%3Apr+is%3Aopen+author%3Asyedmaazsaeed)
