### ISSUE TITLE
I want to add BMI Calculator using python programing

### ISSUE THREAD

**Issue by ArisuAbhilash** [Ayu-hack/Hacktoberfest2024-1#142]

**Comment by Sri5275** [comment]
Hey @Ayu-hack  , can you assign this issue to me labelling it as hacktoberfest-accepted?

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
