### ISSUE TITLE
Issue of input validation in binary search recursion

### ISSUE THREAD

**Issue by shrivalidutt** [Ayu-hack/Hacktoberfest2024-1#143]
There are no checks for user input when reading the size of the array or the elements. If the user enters a non-integer value for size, scanf will fail, and the program may not behave as expected.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
