### ISSUE TITLE
Add a Folder for Dynamic Programming Algorithms

### ISSUE THREAD

**Issue by anushka-220** [Ayu-hack/Hacktoberfest2024-1#149]
I would like to contribute by creating a dedicated folder for Dynamic Programming algorithms. This folder will include solutions to common DP problems such as:

Longest Common Subsequence (LCS)
Knapsack Problem
Coin Change Problem
Matrix Chain Multiplication
Best Time to Buy and Sell Stocks

Adding this folder will help organize and expand the project's collection of algorithms, making it easier for contributors to find and implement DP solutions.

@Ayu-hack    Please assign this issue to me under Hacktoberfest 2024.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
