### ISSUE TITLE
Adding algorithms

### ISSUE THREAD

**Issue by meghanakn473** [Ayu-hack/Hacktoberfest2024-1#152]
Moore's Voting algorithm(Majority element of array), Kadane's Algorithm(Maximum Subarray), Dutch National Flag Algorithm(sorting array of 0's and 1's)

@Ayu-hack please assign me this issue under level 3 , gssoc-extd, hacktoberfest

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by meghanakn473** [comment]
> Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution) Sorry for the inconvenience, and thank you for your understanding! 🙏

Done please assign me over there!!
