### ISSUE TITLE
Disk Usage Analyzer

### ISSUE THREAD

**Issue by pratikj697** [Ayu-hack/Hacktoberfest2024-1#155]
Develop a Python script that analyzes disk usage in a directory and provides insights on the space consumed by each file and subdirectory. It should also be capable of detecting the largest files, and suggest possible candidates for deletion to free up space.

Requirements:
1. Directory Traversal:
Traverse all files and subdirectories in a given directory and compute their sizes.
2. Sorting:
Sort files by size in descending order, and display the largest files.

Edge Cases:
Handle cases where certain files or directories are inaccessible (permissions error).

Please assign this task to me under HacktoberFest 2024.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
