### ISSUE TITLE
Tesla Website Clone

### ISSUE THREAD

**Issue by AmrutaJayanti** [Ayu-hack/Hacktoberfest2024-1#156]
I would like to add `Tesla Website Clone` build using HTML CSS JavaScript.
Please assign me this task under Hacktoberfest2024

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by AmrutaJayanti** [comment]
@Ayu-hack I commented in the new repo . Please consider

**Comment by Ayu-hack** [comment]
okay !
