### ISSUE TITLE
To add Painter's Partition problem 

### ISSUE THREAD

**Issue by moksha-hub** [Ayu-hack/Hacktoberfest2024-1#159]
hello @Ayu-hack can you assign me this to me also with label of hacktoberfest.
Thank you

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
