### ISSUE TITLE
Hey Ayu, wanted to add some important questions in Java for DSA under Hacktoberfest2024

### ISSUE THREAD

**Issue by Kuwarsaab** [Ayu-hack/Hacktoberfest2024-1#160]

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
