### ISSUE TITLE
Add Graph data structure algos and info in c++.

### ISSUE THREAD

**Issue by Mayur-nimkande-20** [Ayu-hack/Hacktoberfest2024-1#161]
Hey @Ayu-hack , wanted to contribute to the repo by adding some basic algos understanding as a beginner contributor. Please, assign this task to me under #hacktoberfest 2024.

**Comment by Rockyoudead8** [comment]
Hey @Ayu-hack , wanted to contribute to this repository by using DSA i have previously implemented DSA in c so it would be helpful for me to easily implement it in c++,  Please assign this  to me under #hacktoberfest2024

**Comment by Mayur-nimkande-20** [comment]
Hey @Ayu-hack  the task has been completed pls accept the pr. Regards Mayur.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
