### ISSUE TITLE
Adding my Conway Game of Life algorithm game

### ISSUE THREAD

**Issue by allanoguis** [Ayu-hack/Hacktoberfest2024-1#167]
I'd like to add my Conway's Game of Life made from ReactJS. 

I wrapped it as a component and it was coded in TypeScript.

![image](https://github.com/user-attachments/assets/666485d9-f2dc-4d6e-bfe5-8021f65327b1)

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
