### ISSUE TITLE
Want to add QR code generator project

### ISSUE THREAD

**Issue by tusharmishra069** [Ayu-hack/Hacktoberfest2024-1#169]
I want to add the QR code generator project in your repo, I have made this project with the help of the python and uses python lib to made this.

**Comment by tusharmishra069** [comment]
kindly assign me this

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏

**Comment by tusharmishra069** [comment]
i have raise the new issue in the recommended repo, kindly assign me
