### ISSUE TITLE
Enhanced Rock Paper Scissors Game

### ISSUE THREAD

**Issue by Cyber-Mukherjee** [Ayu-hack/Hacktoberfest2024-1#18]
Enhanced the python code for Hacktoberfest 2024:

- Add welcome art
- Implement score feature
- Improve play again choice

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Cyber-Mukherjee** [comment]
> Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024. Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄
> 
> 👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/)! ⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

Thank you Ayush. I have already sent a PR, kindly review it.
