### ISSUE TITLE
 Basic Weather App (Using OpenWeatherMap API)

### ISSUE THREAD

**Issue by ananyag309** [Ayu-hack/Hacktoberfest2024-1#19]
add  Basic Weather App (Using OpenWeatherMap API) using python.
This requires an API key from OpenWeatherMap. It fetches the current weather for a given city.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Ayu-hack** [comment]
You can re open the issue or create a new one. 
 More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
