### ISSUE TITLE
 Linked List Problem in Python

### ISSUE THREAD

**Issue by thedarkking01** [Ayu-hack/Hacktoberfest2024-1#195]
@Ayu-hack Hii 😊

Description:
There is a problem with the current implementation of the linked list in Python. The issue appears when performing [specific operation, e.g., insertion/deletion/traversal] on the linked list, causing unexpected behavior or errors.

Steps to Reproduce:
Initialize a linked list using the LinkedList class.
Perform the following operations:
[Operation 1: e.g., Insertion at the head]
[Operation 2: e.g., Deletion of a node]
[Operation 3: e.g., Traversal]
Observe the unexpected behavior.

Expected Behavior:
The linked list should correctly [describe the expected outcome, e.g., update the head node after insertion or return the correct elements during traversal].

Actual Behavior:
[Describe the actual outcome, e.g., Error message, incorrect output, or any other unexpected behavior].

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
