### ISSUE TITLE
Improved UI of dictionary web app

### ISSUE THREAD

**Issue by AvinashUmrao** [Ayu-hack/Hacktoberfest2024-1#213]
Explanation of CSS Changes
Container Styling:

Gradient Background: A light gradient effect makes the container more visually appealing.
3D Shadow Effect: Enhanced the shadow to create a 3D effect, making the container stand out.
Hover Effect: When the container is hovered over, it slightly enlarges, giving a dynamic feel.
Heading Color:

Set a deep blue color for the heading to make it pop against the light background.
Input Field:

Adjusted the border to a color that matches the theme.
Added a focus effect that changes the border color and gives a glowing shadow to emphasize user interaction.
Meaning Container:

Adjusted text color for better readability.
Button:

Added a new button class to style a button for searching words.
Created a hover effect that changes the background color and slightly lifts the button for a tactile feel.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution
