### ISSUE TITLE
Add Bitcoin price calculator

### ISSUE THREAD

**Issue by Aditijainnn** [Ayu-hack/Hacktoberfest2024-1#22]
i want to add Bitcoin price calculator 
please assign this issue to me under hacktober fest;24

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
