### ISSUE TITLE
adding picross game

### ISSUE THREAD

**Issue by Aditijainnn** [Ayu-hack/Hacktoberfest2024-1#24]
Picross
=======

This is a playable [picross puzzle](http://en.wikipedia.org/wiki/Nonogram) generator written in JavaScript

You can access [an online version here](http://liouh.com/picross/)

### Features

* Adjustable grid dimensions (the code is generic and supports any dimension, but a 30x30 game can take up to 2 hours)
* Custom game seeds (allows multiple computers to play using the same starting puzzle configuration)
* Option to toggle crossouts, helping you track numbers that have already been solved
* Auto-saves using HTML5 web storage
* Progress indicator
* Mistakes counter
please assign this to me under gssoc ext and hacktober fest

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏
