### ISSUE TITLE
Add Text_Compression.py File

### ISSUE THREAD

**Issue by bhoomikahm-123** [Ayu-hack/Hacktoberfest2024-1#26]

**Comment by bhoomikahm-123** [comment]
This is a mini project which encodes the text using the Huffman Codes and decodes back to the original text.
Please do assign me with hacktoberfest tag.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts! 🙌

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
