### ISSUE TITLE
Invalid tags in topics section!

### ISSUE THREAD

**Issue by Cyber-Mukherjee** [Ayu-hack/Hacktoberfest2024-1#27]
This is to bring to your notice that the tags under the topics section contains typos. Like "hacktobefest" which is missing an "r". Kindly look into it and make the necessary changes.

**Comment by Ankitmohanty2** [comment]
shall i solve that

**Comment by Cyber-Mukherjee** [comment]
> shall i solve that

Yes, unless the tags are corrected the repo won't be considered for 'Hacktoberfest2024'.

**Comment by Ayu-hack** [comment]
There is no 'r' missing Hackbtoberfest2024 label.

**Comment by Ayu-hack** [comment]
> shall i solve that

No issue in Hacktoberfest2024 label.

**Comment by Cyber-Mukherjee** [comment]
![image](https://github.com/user-attachments/assets/f4301644-adfe-4c40-b820-031ad4b4d3d7)
Kindly look into the highlighted tags in yellow ink.

**Comment by Cyber-Mukherjee** [comment]
![image](https://github.com/user-attachments/assets/946a2980-9499-4cb4-88c3-87a52e5439e2)
Due to the tags, the repo is labelled as not participating in the event

> > shall i solve that
> 
> No issue in Hacktoberfest2024 label.
