### ISSUE TITLE
add CONTRIBUTORS.md and LICENCE 

### ISSUE THREAD

**Issue by YuweAEC** [Ayu-hack/Hacktoberfest2024-1#31]
How about adding a CONTRIBUTORS.md file and a license to this repo?

**Comment by YuweAEC** [comment]
please do assign this issue to me by adding hacktoberfest24 tag

**Comment by Ayu-hack** [comment]
It is already. Please bring something new.There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
