### ISSUE TITLE
Add Tic Tac Toe Game

### ISSUE THREAD

**Issue by ghost** [Ayu-hack/Hacktoberfest2024-1#38]
It is a simple Tic Tac Toe Game that represents the numbers using C Language.

please assign this to me under  hacktober fest.

**Comment by Ayu-hack** [comment]
Please bring something new. It is already there.
There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
