### ISSUE TITLE
Real-Time Stock Price Tracker Using Binary Search Trees

### ISSUE THREAD

**Issue by pratikj697** [Ayu-hack/Hacktoberfest2024-1#45]
I want to perform  task for such system to track the real-time stock prices of a company. The system should be able to insert new stock prices, retrieve the minimum and maximum stock prices, and return the median price efficiently. You are required to design this system using a data structure that supports efficient insertion and retrieval operations.

can you please assign me this under hactoberfest 2024.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
