### ISSUE TITLE
A Simple C++ code that generates a 3D spinning donut 🍩

### ISSUE THREAD

**Issue by blunterdecosta123** [Ayu-hack/Hacktoberfest2024-1#50]
This is a fun project to create a 3D spinning Donut that will create a visually appealing effect on the user when ran on the console in C++.

Please assign me this under hactoberfest 2024.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
