### ISSUE TITLE
Simple Calculator using python

### ISSUE THREAD

**Issue by ananyag309** [Ayu-hack/Hacktoberfest2024-1#55]
A basic calculator that performs addition, subtraction, multiplication, and division.

**Comment by DevendraJaiswal074** [comment]
Hii @ananyag309 
I am a beginner, I'd love the opportunity to tackle this issue Could you assign it to me?

**Comment by Ayu-hack** [comment]
Bring something new and unique.
There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Ayu-hack** [comment]
> Hii @ananyag309 I am a beginner, I'd love the opportunity to tackle this issue Could you assign it to me?

you should highlight some new issue and then make PR.

There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!
