### ISSUE TITLE
Trapping Rain Water problem

### ISSUE THREAD

**Issue by TanushreeBorase** [Ayu-hack/Hacktoberfest2024-1#6]
I would like to add solution to trapping rain water problem of dsa in cpp. Please assign me this issue under hacktoberfest 2024.

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

**Comment by Ayu-hack** [comment]
There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on Linkedin
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Gungunmi12** [comment]
I would Like to add the solution of this can u pls assign it to me

**Comment by siya100** [comment]
hey @Ayu-hack please assign this issue to me
