### ISSUE TITLE
A simple habit tracker using python with UI using Tkinter

### ISSUE THREAD

**Issue by Apoorva-Datir** [Ayu-hack/Hacktoberfest2024-1#60]
Hi I am willing to work on this issue. Can you please assign this to me under hacktoberfest2024 tag ?

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Apoorva-Datir** [comment]
@Ayu-hack Please review this PR

**Comment by Ayu-hack** [comment]
Merged. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏
