### ISSUE TITLE
Proposal : Adding Ternary Search Program 

### ISSUE THREAD

**Issue by 1-SubhamSingh** [Ayu-hack/Hacktoberfest2024-1#63]
Can you please assign me this task under Hacktoberfest 2024 label :) @Ayu-hack

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by 1-SubhamSingh** [comment]
@harendrabhardwaj Could you please close your PR , this task was assigned to me.
        Thank you.
