### ISSUE TITLE
Rajasthan Chatbot - An AIML python project 

### ISSUE THREAD

**Issue by DevDatir** [Ayu-hack/Hacktoberfest2024-1#68]
Hey,

I want to contribute to this repo with my chatbot project which allows users to get information about Engineering colleges of Rajasthan.
Can you please assign this to me under the hacktoberfest2024 tag?

**Comment by Ayu-hack** [comment]
1. Assigned. 
2. Please share the 2-4 screenshot of working chatbot in PR to get that merged.

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by DevDatir** [comment]
@Ayu-hack Please review this PR
