### ISSUE TITLE
I would like to add Solution for "Container with most Water" Problem

### ISSUE THREAD

**Issue by ghost** [Ayu-hack/Hacktoberfest2024-1#71]
This issue aims to add a coding problem titled "Container with most Water" along with its solution to the repository.

Problem Statement:
You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).

Find two lines that together with the x-axis form a container, such that the container contains the most water.

Return the maximum amount of water a container can store.

Example 1:
Input: height = [1,8,6,2,5,4,8,3,7]

Output: 49

Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.

I would like to contribute to this repo under hacktoberfest, kindly assign me this issue. @Ayu-hack

**Comment by Ayu-hack** [comment]
Assigned.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by ghost** [comment]
Thank you.i'll start working on this
