### ISSUE TITLE
Request for Adding Various Graph Algorithms

### ISSUE THREAD

**Issue by Singhal1808** [Ayu-hack/Hacktoberfest2024-1#73]
Hi @Ayu-hack,
I am participating in Hacktoberfest 2024 and would like to contribute to it by adding several important graph algorithms. These algorithms are foundational in computer science, particularly for pathfinding and graph analysis.They will serve as valuable resources for newcomers to understand graph theory and its applications.

I plan to implement the following algorithms:
-> Dijkstra's Algorithm: For finding the shortest path in weighted graphs.
-> Kruskal’s Algorithm: To find the Minimum Spanning Tree (MST) using the greedy approach.
-> Prim's Algorithm: Another method to find the MST, particularly suitable for dense graphs.
-> Bellman-Ford Algorithm: Useful for graphs with negative weights.
-> Floyd-Warshall Algorithm: For finding shortest paths between all pairs of vertices.
-> Depth-First Search (DFS): A fundamental graph traversal algorithm.
-> Breadth-First Search (BFS): Another key traversal method.

Implementing these algorithms can broaden the scope of potential use cases for the project, attracting more users and contributors.
I would appreciate it if you could assign this to me.

**Comment by Ayu-hack** [comment]
Assigned.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
