### ISSUE TITLE
I would like to add a C++ file with some DSA problems.

### ISSUE THREAD

**Issue by dhruvaaArya05** [Ayu-hack/Hacktoberfest2024-1#78]
Hi @Ayu-hack,
I am participating in Hactoberfest 2024 as I am new to the open source I would like to contribute by adding a C++ file in which some beginner level DSA problem will be there.

The DSA problem Topic will be Arrays, Searching algorithms and Sorting Algorithm.
Kindly assign me this issue under the Hacktoberfest Label.
Thank you.

**Comment by Ayu-hack** [comment]
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by abhisheksaxena15** [comment]
Hi @Ayu-hack 

I hope you’re doing well! I’m really excited to be participating in Hacktoberfest 2024 this year. As I’m completely new to open source, I’d love to contribute by adding a C++ file that covers some beginner to advance level DSA problems.

I’m planning to focus on topics on all the major and minor topics that will cover DSA and will be helpful even for a beginner like  Linked List , all Searching algorithms, and Sorting algorithms and Graphs and trees. With extra  interview asked DSA problems which can be further completed by the attendee.  Would you be able to assign me this issue under the Hacktoberfest label? I’m eager to get started!

Thank you

Best regards,
Abhishek Saxena
