### ISSUE TITLE
I would like to add JS Coding question

### ISSUE THREAD

**Issue by AthulKkumar** [Ayu-hack/Hacktoberfest2024-1#79]

**Comment by Ayu-hack** [comment]
Share the screenshot of working in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by mohamedfarhan-m** [comment]
hi, @AthulKkumar can you specify a bit more on this issue.
I am interested and have experience in javascript, wanted to contribute in it.

**Comment by Ayu-hack** [comment]
Find the issue by yourself.

**Comment by Ayu-hack** [comment]
You can work portfolio repo. Check out my GitHub profile. It is also a part of hacktoberfest.

**Comment by AthulKkumar** [comment]
@Ayu-hack  Permission got denied to push bro ,need the permission for it to push it the repo
