### ISSUE TITLE
Hangman Game with ASCII Art

### ISSUE THREAD

**Issue by ananyag309** [Ayu-hack/Hacktoberfest2024-1#80]
A fun command-line version of the classic Hangman game with ASCII art. You can play this right from the terminal.

**Comment by Ayu-hack** [comment]
Nice! 
Please share the screenshot in PR, to get it merged.
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts!
