### ISSUE TITLE
Implement Various Approaches to Calculate the Greatest Common Divisor (GCD)

### ISSUE THREAD

**Issue by prajwaln07** [Ayu-hack/Hacktoberfest2024-1#83]
# Implement Various Approaches to Calculate the Greatest Common Divisor (GCD)

This issue aims to implement and compare multiple approaches to calculate the Greatest Common Divisor (GCD) of two integers. The objective is to showcase different algorithms with varying levels of efficiency, following best coding practices.

## Proposed Approaches:
1. **Brute Force Method**: 
   - A simple approach that checks all integers from 1 to the minimum of the two input numbers and finds the largest integer that divides both.
   - **Time Complexity**: O(min(a, b))

2. **Euclidean Algorithm**: 
   - An optimized method based on the principle that GCD(a, b) = GCD(b, a % b). This algorithm significantly reduces the number of iterations required.
   - **Time Complexity**: O(log(min(a, b)))

3. **Binary GCD Algorithm (Stein's Algorithm)**: 
   - The most efficient method that uses binary operations to find the GCD. It employs bit manipulation for enhanced performance.
   - **Time Complexity**: O(log(min(a, b)))

## Tasks:
* Implement each of the three methods in separate functions.
* Use meaningful variable names and adhere to standard coding practices.
* Provide clear documentation and comments in the code for better understanding.
* Write test cases to validate the correctness of each implementation.

This issue will help in understanding the differences in algorithmic efficiency and practical application in solving the GCD problem. It will also serve as a valuable contribution to the repository, enriching the available resources for users interested in algorithm implementation.

@Ayu-hack  please assign me this issue under hacktober-fest.

**Comment by Ayu-hack** [comment]
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
