### ISSUE TITLE
Request for adding Most Common and important java script concept for interviews with theory and example .

### ISSUE THREAD

**Issue by aakash-sharma25** [Ayu-hack/Hacktoberfest2024-1#86]
Hi @Ayu-hack 
I am participating in Hacktoberfest 2024 and would like to contribute to it by adding several **important and most common java script interview questions .**
I am using **theory** to explain and below the theory there is **code** so that the one who is reading can also see its implementation and run it .

I would appreciate it if you could assign this issue to me under hacktober-fest.

**Comment by Ayu-hack** [comment]
Already exists. Bring something new n unique.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
