### ISSUE TITLE
Want to add solution of leetcode problem Q200 Number of Islands

### ISSUE THREAD

**Issue by Aditijainnn** [Ayu-hack/Hacktoberfest2024-1#9]
Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands.

An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are all surrounded by water.
Please assign this issue to me in hacktoberfest'24

**Comment by Ayu-hack** [comment]
Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024.
Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄

👉 Do follow my GitHub and connect with me on Linkedin
⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

**Comment by Aditijainnn** [comment]
> Assigned. There are more repos where you can make pull requests, and your contributions will definitely be accepted! They are also part of Hacktoberfest 2024. Don’t forget to tag me in your LinkedIn certificate post if possible. Thank you! 😄
> 
> 👉 Do follow my GitHub and connect with me on Linkedin ⭐ Also, don't forget to star these repos to stay updated for next year's Hacktoberfest!

PLEASE LEVEL IT ALSO
