### ISSUE TITLE
Solving n queens problem in Ruby programming language

### ISSUE THREAD

**Issue by Ayushi40804** [Ayu-hack/Hacktoberfest2024-1#94]
n-queens problem solution using backtracking in ruby language for hacktoberfest 2024.
What is N-Queen problem?
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other.
please assign this to me under Hacktoberfest label

**Comment by Ayu-hack** [comment]
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!

**Comment by mohamedfarhan-m** [comment]
hi, @Ayu-hack  please assign me this issue under Hacktoberfest label

**Comment by Ayushi40804** [comment]
#103 already given pull request for this issue

**Comment by Ayu-hack** [comment]
⭐ Please star this repo as a token of appreciation for the efforts! 🙌

**Comment by Ayu-hack** [comment]
This has been excluded from hacktoberfest as someone falsely reported the repos.
Please consider contributing to this repo: https://github.com/Ayu-hack/Hacktoberfest2024
Sorry for the inconvenience, and thank you for your understanding! 🙏
