### ISSUE TITLE
Request to add Ai text to Image using Hugging Face

### ISSUE THREAD

**Issue by aakash-sharma25** [Ayu-hack/Hacktoberfest2024-1#97]
Hi @Ayu-hack 
I am participating in Hacktoberfest 2024 and would like to contribute to it by adding PixelVerse : Ai Text to Image using Hugging Face Api which generates images based on the prompt given . It uses Hugging face model to generate the images .

I would appreciate it if you could assign me this issue under hacktoberfest24 label.

**Comment by Ayu-hack** [comment]
Great project!
Assigned. More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
