### ISSUE TITLE
Request to Add Heap Sort - C++

### ISSUE THREAD

**Issue by yorgokennos** [Ayu-hack/Hacktoberfest2024-1#99]
Glancing at the list of current sorting algorithms heap sort appears to be missing. 

Time complexity of O (n log n).

    Treat Array as Complete Binary Tree
    Build a Max Heap
    Sort array by placing largest at end

![image](https://github.com/user-attachments/assets/1e1f237e-736b-439f-96d9-14f4e89a6fc8)

Please assign me this issue with hacktoberfest label <3

**Comment by Ayu-hack** [comment]
Already exists. Bring something new n unique.
More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄

👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
